version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"   # според Dockerfile-от што го имаш за backend
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/todolist

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"    # nginx работи на 80-та порта, map-ирана на 3000
    depends_on:
      - backend

volumes:
  mongo_data:
