apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: katerina-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: katerina11/backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-uri
